server:
  port: 8080
  baseurl: http://dev.faraone.ovh:81
  error:
    whitelabel:
      enabled: false
grpc:
  server:
    port: 3030
  client:
    bank:
      address: dns:///bank:3030
      negotiationType: PLAINTEXT
    parent:
      address: dns:///parent:3030
      negotiationType: PLAINTEXT

queue:
  bank:
    deposit: bank-deposit
    withdrawal: bank-withdrawal
  transfers: transfers
  market:
    sell: market-sell
    purchase: market-purchase
  transactions: transactions
  wallet:
    creation: wallets-creation
    deletion: wallets-deletion
  emails: emails
  account:
    creation: krypto-accounts
    deletion: krypto-account-deletion

spring:
  application:
    name: krypto
  activemq:
    packages:
      trusted:
        - com.bok.parent
        - com.bok.krypto
        - com.bok.bank
        - java.lang
        - java.sql
    user: developer
    password: password4testing
    broker-url: tcp://activemq:61616

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://bok.faraone.ovh:3307/krypto
    username: developer
    password: password4testing
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

coinmarket:
  endpoint: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  api-key: 2381b575-4d98-414d-aca3-b52be8aa66e3
  start: 1
  limit: 10
  base-currency: USD

