server:
  port: 8080
  baseurl: http://dev.faraone.ovh:81

active-mq:
  transfers-queue: transfers
  market-sell-queue: market-sell
  market-purchase-queue: market-purchase
  prices-topic: prices
  krypto-users: krypto-accounts
  transactions-queue: transactions
  wallets-queue: wallets
  emails-queue: emails
  broker-url: tcp://activemq:61616

spring:
  application:
    name: krypto

  activemq:
    packages:
      trusted: com.bok.krypto.model

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://dev.faraone.ovh:3307/krypto
    username: developer
    password: password4testing

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

coinmarket:
  endpoint: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  api-key: 2381b575-4d98-414d-aca3-b52be8aa66e3
  start: 1
  limit: 10
  base-currency: USD

