// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: krypto.proto

package com.bok.krypto.integration.grpc;

/**
 * Protobuf type {@code AccountCreationRequest}
 */
public final class AccountCreationRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:AccountCreationRequest)
        AccountCreationRequestOrBuilder {
    public static final int ACCOUNTID_FIELD_NUMBER = 1;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:AccountCreationRequest)
    private static final com.bok.krypto.integration.grpc.AccountCreationRequest DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<AccountCreationRequest>
            PARSER = new com.google.protobuf.AbstractParser<AccountCreationRequest>() {
        @java.lang.Override
        public AccountCreationRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new AccountCreationRequest(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.bok.krypto.integration.grpc.AccountCreationRequest();
    }

    private long accountId_;
    private volatile java.lang.Object email_;
    private byte memoizedIsInitialized = -1;
    // Use AccountCreationRequest.newBuilder() to construct.
    private AccountCreationRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private AccountCreationRequest() {
        email_ = "";
    }

    private AccountCreationRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        accountId_ = input.readInt64();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        email_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.bok.krypto.integration.grpc.KryptoProto.internal_static_AccountCreationRequest_descriptor;
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.bok.krypto.integration.grpc.AccountCreationRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.bok.krypto.integration.grpc.AccountCreationRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<AccountCreationRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new AccountCreationRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.bok.krypto.integration.grpc.KryptoProto.internal_static_AccountCreationRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.bok.krypto.integration.grpc.AccountCreationRequest.class, com.bok.krypto.integration.grpc.AccountCreationRequest.Builder.class);
    }

    /**
     * <code>int64 accountId = 1;</code>
     *
     * @return The accountId.
     */
    public long getAccountId() {
        return accountId_;
    }

    /**
     * <code>string email = 2;</code>
     *
     * @return The email.
     */
    public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            email_ = s;
            return s;
        }
    }

    /**
     * <code>string email = 2;</code>
     *
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
    getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            email_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (accountId_ != 0L) {
            output.writeInt64(1, accountId_);
        }
        if (!getEmailBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (accountId_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(1, accountId_);
        }
        if (!getEmailBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.bok.krypto.integration.grpc.AccountCreationRequest)) {
            return super.equals(obj);
        }
        com.bok.krypto.integration.grpc.AccountCreationRequest other = (com.bok.krypto.integration.grpc.AccountCreationRequest) obj;

        if (getAccountId()
                != other.getAccountId()) return false;
        if (!getEmail()
                .equals(other.getEmail())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getAccountId());
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AccountCreationRequest> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.bok.krypto.integration.grpc.AccountCreationRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * Protobuf type {@code AccountCreationRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:AccountCreationRequest)
            com.bok.krypto.integration.grpc.AccountCreationRequestOrBuilder {
        private long accountId_;
        private java.lang.Object email_ = "";

        // Construct using com.bok.krypto.integration.grpc.AccountCreationRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.bok.krypto.integration.grpc.KryptoProto.internal_static_AccountCreationRequest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.bok.krypto.integration.grpc.KryptoProto.internal_static_AccountCreationRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.bok.krypto.integration.grpc.AccountCreationRequest.class, com.bok.krypto.integration.grpc.AccountCreationRequest.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            accountId_ = 0L;

            email_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.bok.krypto.integration.grpc.KryptoProto.internal_static_AccountCreationRequest_descriptor;
        }

        @java.lang.Override
        public com.bok.krypto.integration.grpc.AccountCreationRequest getDefaultInstanceForType() {
            return com.bok.krypto.integration.grpc.AccountCreationRequest.getDefaultInstance();
        }

        @java.lang.Override
        public com.bok.krypto.integration.grpc.AccountCreationRequest build() {
            com.bok.krypto.integration.grpc.AccountCreationRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.bok.krypto.integration.grpc.AccountCreationRequest buildPartial() {
            com.bok.krypto.integration.grpc.AccountCreationRequest result = new com.bok.krypto.integration.grpc.AccountCreationRequest(this);
            result.accountId_ = accountId_;
            result.email_ = email_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.bok.krypto.integration.grpc.AccountCreationRequest) {
                return mergeFrom((com.bok.krypto.integration.grpc.AccountCreationRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.bok.krypto.integration.grpc.AccountCreationRequest other) {
            if (other == com.bok.krypto.integration.grpc.AccountCreationRequest.getDefaultInstance()) return this;
            if (other.getAccountId() != 0L) {
                setAccountId(other.getAccountId());
            }
            if (!other.getEmail().isEmpty()) {
                email_ = other.email_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.bok.krypto.integration.grpc.AccountCreationRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.bok.krypto.integration.grpc.AccountCreationRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <code>int64 accountId = 1;</code>
         *
         * @return The accountId.
         */
        public long getAccountId() {
            return accountId_;
        }

        /**
         * <code>int64 accountId = 1;</code>
         *
         * @param value The accountId to set.
         * @return This builder for chaining.
         */
        public Builder setAccountId(long value) {

            accountId_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>int64 accountId = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearAccountId() {

            accountId_ = 0L;
            onChanged();
            return this;
        }

        /**
         * <code>string email = 2;</code>
         *
         * @return The email.
         */
        public java.lang.String getEmail() {
            java.lang.Object ref = email_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                email_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string email = 2;</code>
         *
         * @param value The email to set.
         * @return This builder for chaining.
         */
        public Builder setEmail(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            email_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email = 2;</code>
         *
         * @return The bytes for email.
         */
        public com.google.protobuf.ByteString
        getEmailBytes() {
            java.lang.Object ref = email_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                email_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string email = 2;</code>
         *
         * @param value The bytes for email to set.
         * @return This builder for chaining.
         */
        public Builder setEmailBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            email_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string email = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearEmail() {

            email_ = getDefaultInstance().getEmail();
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:AccountCreationRequest)
    }

}

