# ACTIVE-MQ CONFIG
active-mq:
  transfers-queue: transfers
  market-sell-queue: market-sell
  market-purchase-queue: market-purchase
  prices-topic: prices
  users-queue: users
  transactions-queue: transactions
  wallets-queue: wallets
  emails-queue: emails
  broker-url: tcp://active-mq:61616

spring:
  application:
    name: krypto
  activemq:
    packages:
      trusted: com.bok.krypto.model
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://krypto-db:3306/kryptodb
    username: krypto
    password: krypto
  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

coinmarket:
  endpoint: https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest
  api-key: 2381b575-4d98-414d-aca3-b52be8aa66e3
  start: 1
  limit: 10
  base-currency: USD

