# ACTIVE-MQ CONFIG
active-mq:
  transfers-queue: transfers
  orders-queue: orders
  broker-url: tcp://active-mq:61616

spring:
  activemq:
    packages:
      trusted: com.bok.krypto.model
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://krypto-db:3306/kryptodb  # HSQL DB CONFIG
    username: krypto
    password: krypto
  jooq:
    sql-dialect: org.hibernate.dialect.MariaDBDialect
  jpa:
    hibernate:
      ddl-auto: update

coinmarket:
  api-key: '2381b575-4d98-414d-aca3-b52be8aa66e3'
  start: 1
  limit: 10
  base-currency: USD

